log_level = "warn"
outputs = { Targets = ["DP-1", "DVI-D-1"] }
position = "Top"
app_launcher_cmd = "wofi --show drun"

[modules]
left = [ [ "appLauncher", "Workspaces" ] ]
center = [ "WindowTitle", "KeyboardLayout" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Memory", "Settings" ] ]

#[updates]
#check_cmd = "checkupdates; paru -Qua"
#update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "ó±—¼"
command = "wofi --show drun"

[window_title]
truncate_title_after_length = 100

[keyboard_layout.labels]
"English (US)" = "us"
"Russian"      = "ru"
"Ukrainian"    = "ua"

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "impala"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "bluetui"

[appearance]
style = "Islands"

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14
